name: Build and Push to ACR

on:
  push:
    branches:
      - master
    paths:
      - 'apps/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no ACR
        run: |
          az acr login --name mgsdevopsacr

      - name: Build e Push da imagem
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/linkding:${{ github.sha }} ./apps/base/linkding
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/linkding:${{ github.sha }}
