apiVersion: v1
kind: Secret
metadata:
    name: app-secret
type: Opaque
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:UGPy,iv:qdCzV3M4nu0hs3gPlv7/etc6m/Hyh2tA8G0MuKwU2VA=,tag:dcHi9TEzQMXZqVJoNzl0yQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:j5pp,iv:Pirgo5g3wbO4nN8mDAl+q/+s+XlAADdEwIHm5R063Vs=,tag:UG+Ebq5xS0G6Fb6rqTihCw==,type:str]
sops:
    age:
        - recipient: age1rn87v7zw8ga887z9c7whnuuyuxex3rrcelaa9nthme9p5h862ycqxeag2e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNWJBdVBMQ1lTUmNtbXR0
            bzRxb0dIRWhWZGdNdytqb2pQNGQ3YmZVTHhJCmFRUDlsQW13U1RzRWF3RkZINFhY
            VGNJSWxML2hUVXN3dkRIYWx1OGFSSzQKLS0tIHIxZFZWZHVrbC9IMm1GdEhnY2ZQ
            WTZaaHo5eUE3ZmlXbXFXb09VakJSQWsK15YyRVIHIAPd6frB1Q9UFIMn8SMUv997
            IjJ+xZYcMr9+WA2sjbkPoRZx94uuYMENtPX0MalPaathtLGqnycc2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-04T18:26:28Z"
    mac: ENC[AES256_GCM,data:TNvBoYug2N+8WfHaFN0clPlHPalFKH1U8scFTYfJgboHHlC1V/yaqc4PqiL1JxmaeMYhi/1zdepiSyZQpcsJK58TAqP6AR4M91+TVnsZ/QRLUZFiDSQHd6RzUlIxfdYmw9ltzHQsFFiZ136/iEo5wmjsXw6FkL3QMk/c8R/aCwg=,iv:adzDlgANsvFbYU+nhFSc86yezQoaqA82mQ6ouobjHvA=,tag:qnY//mxatGAkBUEXd4oNeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
