apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:cW2WtQ==,iv:/eQ2yF2Ind5RDJlY/ABPMgHPV2F+noLWKZjyt58fPAA=,tag:u4oTKndcS7kI4iVY5BFtEQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:yF0Ftw==,iv:JFqObQOCTmSl+CBFucPHLwXBKXEeGLX2kNbMw5YK7xI=,tag:IUP4B0bTpW/Zmw8Mfe2y+Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1rn87v7zw8ga887z9c7whnuuyuxex3rrcelaa9nthme9p5h862ycqxeag2e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOUFIajZoS2F4SDJoTm1j
            WU1xNWxEYlNnTG4vdWFpRUtwb1pwYXlDank4Ck85YUIwZ2xGd1ZHaUNGUUtxMnFK
            UDk5cHptQnhvOEZLK2NEVDR6U2tpQVEKLS0tIGNEQnNlRUdRVkZUaUNwRXk4dHZV
            ZytwS2syRlNnL2Z6SWw5V1JSdy91dEUKEdRtzwVAv0EYisJAkZCp4t/kWSoGlh56
            NEiX+KwTtem0elhsoOqzTIvH0Tl52uVU8TkicaW4bxoS+OJdQA/M7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-04T19:07:04Z"
    mac: ENC[AES256_GCM,data:qix/RMBP6QtN6m5Lpig+b2Zw+j+6moPCDeDlpzIDmyB0cv3D0AVO2F+HtiqLyknIwOkk1j9/bKSrbStmRBOq9enOMHxGJMgBTiPkcbvaPs4YIvWQvrebK/6eCArKNI/ZPYomRKecFqn+I8MoNoXgR5JJos3DaOTnjwGYW3Dt2Ww=,iv:d34su/1AGoJsqBhQFHQxb1oH2NFnEPwTeBGm9CVH7Ak=,tag:/uQ0LtBMyQRnQRfXG6l0aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
