apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
type: Opaque
stringData:
    tunnel-credentials.json: ENC[AES256_GCM,data:TKF9e3RAz7N7WmMhSPyGi6ArjwoQ7SfBr73uAxlbODUYfGeZLMv5rslR0Jcqk9GJDu+2ow9Sr6Jb1iygLmGmvPrqcLcEdqNq8gWhUFD54M/KRywvrhR4CuakMN+yXdrzhgP62tdBWPwxHBoMnRycFHRFaSmAhEKes42yp1tQCSvy5JPBFfmvW66zFm0ce8F1XB9uP3RWI3u+oAueG9o82RkKUThI0Rp/bV+vaAZetUPM8Fp6D+6KQWw36YMA7piQeA==,iv:M0DSYf+i/jiswNtGeY0zezf4ZC8p+aPi3+lEm+4LN8c=,tag:waUHI2f4IJ/bGC92VSFa/A==,type:str]
sops:
    age:
        - recipient: age1rn87v7zw8ga887z9c7whnuuyuxex3rrcelaa9nthme9p5h862ycqxeag2e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SXpXeCt1dEtPY1M0Rkdm
            L1hhT25ndnZPUXJhbDI2ajFiOGp1SW5kVXg0CkNEVmhnQlN2UjgySTlrem9PRG9Y
            R1FvajVmcTNHZE1ISFVVaE1zSDBRL00KLS0tIG5RTXAyZFdxbDYwcG9RNERKWWFo
            RU9ValZ3T3BMNXV1WDJpb0pwYnhzTFUKVS8PHg9HPyViuC7MwZ5AY3PSNTl7F/Vx
            /wt0Am8Gsi/khplOIfLUO971hymolS8D6JxkrEXHrAxXQKijJHNYXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-04T17:44:43Z"
    mac: ENC[AES256_GCM,data:5MgsWxc0xQq1sexnjiZJmcJMR2UKz9WzYI72b4Pm18r5Yft/ZkF0Qr1tXuUcf8S88iMiLh2N0AqW9q5RUjK3tiiKmqxOalG8PhN+dXpV8cfQvberAUM1c29i7gxeRbUVisuTVuDMyDNCmTBRZcpbx/Ap4wqtG93P0UkTpc3/SRg=,iv:/nkKCpg/Seliq+GRgk/ecoTL3pTPL3/yraFa8rad9Sg=,tag:71NHMtnIx3Nr5r2kl8vjBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
