apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0
          env:
            - name: LD_SUPERUSER_NAME 
              valueFrom:
                secretKeyRef:
                  name: app-secret 
                  key: username

            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: app-secret
                  key: password

          ports:
          - containerPort: 9090
              
          securityContext:
            allowPrivilegeEscalation: false 

          volumeMounts:
            - mountPath: "/etc/linkding/data"
              name: linkding-data
      volumes:
         - name: linkding-data
           persistentVolumeClaim:
             claimName: linkding-data-pvc

